# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-14 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybarcapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('actionType', models.CharField(choices=[('Admin', 'admin'), ('Read', 'read'), ('Write', 'write'), ('Delete', 'delete')], default='Read', max_length=255)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm', to='mybarcapp.Resource')),
                ('usersRole', models.ManyToManyField(to='mybarcapp.User')),
            ],
        ),
    ]
