# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-14 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybarcapp', '0002_resource_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='usersRole',
            new_name='users_Role',
        ),
        migrations.AlterField(
            model_name='role',
            name='actionType',
            field=models.CharField(choices=[('Read', 'read'), ('Write', 'write'), ('Delete', 'delete')], default='Read', max_length=255),
        ),
    ]
