# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybarcapp', '0005_remove_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
