# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybarcapp', '0006_auto_20200314_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, to='mybarcapp.User'),
        ),
    ]
