# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-14 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybarcapp', '0007_auto_20200314_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='actionType',
            new_name='action_type',
        ),
    ]
