# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybarcapp', '0010_auto_20200315_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
